TypesettingTools/Aegisub

- src/colour_button.cpp
- src/subtitles_provider_libass.cpp
- src/video_frame.cpp
- src/video_provider_dummy.cpp
boost/gil.hpp was added in 1.68 and boost/gil/gil_all.hpp removed in 1.69.
Builds for me on 1.69.
1.68 was released in August 2018, which was 5 months ago. It's not been long enough to skip the `#if` check.
> Adjust boost gil header paths for boost 1.69

- packages/win_installer/fragment_associations.iss
- src/command/audio.cpp
- src/command/video.cpp
- src/project.cpp
Recognizes .opus as audio (both in-application Open dialogue and Windows Explorer file definition).
Recognizes .h264 and .hevc as a video file, not a AV container.
> Recognize .opus as an audio format, .h264 .hevc as video formats

- tools/version.sh
It was generated in the `build` directory and not in the root where the include points to. I don't know if this is the "intended" target directory, but it kind of makes sense. I also don't know where or how the xml file is used, but I "fixed" its path as well.
I also added a commit I did long ago to use the proper git command for the revision number.
> Fix git_version.h generation

- subprojects/luajit/meson.build
This pull request intentionally solves this in the dumbest and ugliest way possible in order to force Ryan to come up with something better (or alternatively conclude that this is actually the way to do it).
> meson: Apply Lua 5.2 compat flags to both native and non-native builds

- meson.build
- tools/version.ps1
- tools/version.sh
Also fix incorrect use of return outside function. Fixes #80
> meson: don't generate git_version.xml and don't regenerate git_version.h on windows

- meson.build
Mostly just enables logging to stdout and what appears to be some sanity checking of the Lua stack, as well as adds `[DEBUG]` to the window title.
> meson: set _DEBUG on all platforms for debug builds

- meson.build
- src/dialog_fonts_collector.cpp
- src/dialog_translation.cpp
- src/frame_main.cpp
- src/subs_edit_ctrl.cpp
On Linux a bunch of GTK errors/warnings are still printed to the console but I'm not particularly worried about them at the moment. The application itself seems to work.
I tested building on Windows too, and the assertions are gone, though it crashed for me whenever I tried to load a video. I don't think that's related to this, though.
> Fix two wx assertions

- src/dialog_resample.cpp
- src/preferences.cpp
One to remove an assertion error, another to make a text field usable.
> Small wx 3.1 fixes

- meson.build
- subprojects/packagefiles/boost/libs/locale/meson.build
Inspired by #105, but with more robust logic and applied across the build. Should match what the libass port is doing as well.
> meson: improve iconv detection

- src/ass_dialogue.cpp
- src/ass_style.cpp
- src/dialog_style_editor.cpp
- src/subs_edit_box.cpp
Previously, margins were clamped to 0..9999, but negative margins are well supported by most renderers. In addition, previously lua automations automations were able to produce these negative margin values, and they would be saved correctly. However, re-opening the file would clamp the values, and they could not be edited in the edit box.
This changes the clamping to be -9999..99999, and allows entering (and editing) negative values in all relevant fields. In addition, this makes the subtitle edit box margin fields take 5 characters instead of 4 to accommodate negative numbers up to 9999 (also the reason for raising the upper bound).
> Fix negative margin handling (closes #104)

- meson.build
- meson_options.txt
Because I got tired of manually editing the meson.build file whenever I wanted to test something with wx 3.1 on Linux.
> meson: add option to specify wxWidgets version

- .github/workflows/ci.yml
- subprojects/freetype2.wrap
Tested installer on Windows, no more missing dlls. Depends on TypesettingTools/libass#10.
> meson: Fix Windows artifacts

- subprojects/packagefiles/luajit/src/host/meson.build
Meson thought that a ARM64 cpu is aarch64, while
LuaJIT only provided a file for "arm64". Since there is
no difference but the name between aarch64 and arm64, I
choose to bind aarch64 -> arm64.
Signed-off-by: Yi-Jyun Pan <pan93412@gmail.com>
> meson: luajit: allow to build in ARM64

- src/subtitles_provider_libass.cpp
- subprojects/csri/backends/libass/libass_csri.c
- subprojects/ffmpeg.wrap
Since ASS rendering depends on the storage size of the video libass
needs to know about it to render the subtitles correctly. If it isn't
told about the storage size libass uses the value from PlayRes{X,Y} as
a guess, but this isn't always correct.
With Aegisub currently always rendering at storage resolution
this ends up the same as the frame size.
---
I'm confident the “rendering size == storage size” assumption holds true for Aegisub’s subtitle preview. From a glance it also appears to hold true for Aegisub’s csri frontends for CLI and AviSynth, but I'm less confident about those two. On the other hand, since csri currently only gets one size: if it isn't correct, this should in theory also affect VSFilter-based backends.
You can see the different rendering on the following sample (to …
> Fix rendering with libass to match xy-VSFilter

- automation/include/unicode-monkeypatch.lua
Line 68: Syntax error -> without the parentheses, some automation scripts will raise the error "cannot convert 'function' to 'int'" when being loaded
Line 72: Will raise the error "attempt to concatenate 'string' and 'char *'
Line 128-129: code is changed so the command can be executed
> Fix errors when automation scripts being loaded and os.execute not working

- .github/workflows/ci.yml
- .gitignore
- libaegisub/include/libaegisub/audio/provider.h
- packages/win_installer/fragment_codecs.iss
- packages/win_installer/fragment_translations.iss
- subprojects/ffms2.wrap
- tools/osx-fix-libs.py
- Fix the current compile error when building on Linux (say, using the AUR package).
- Fix missing file errors for Avisynth and the localization files when building the installer on windows.
Tested with:
- On Linux: Latest Arch Linux
- On Windows: VS2019 and Meson 0.61.2
The CI builds also [finish](https://github.com/arch1t3cht/Aegisub/actions/runs/2599195494) without errors on Windows and Linux now, although that CI run is with a few more commits on top of it. These other commits are also various bugfixes, but for those I'm not sure if you want them PR'd. Let me know if I should add any of them.
I didn't test VS2022 on my machine though (reinstalling all of that is too much of a pain right now...) and a while ago I ran into some compilation errors with `stdatomic.h` on VS2022 only, but …
> meson: fix linux build and windows installer

- meson.build
Meson 0.60.0 adds support for an "iconv" dependency that always does the right thing for you, so that you don't need to think about it. It also has some side advantages:
- you can do dependency fallback, and `--force-fallback-for=iconv` works
- it logs one line, not two, and that is "dependency found? yes or no"
Since Aegisub doesn't mandate the use of such new versions of Meson, we cannot assume the dependency works. Instead, adapt to the version of Meson being used: on new enough versions of Meson, use the new dependency, but on older versions of Meson, use the pre-existing logic, which isn't as nice but has been producing correct results so far.
> meson: use best practices lookup for iconv support

- .github/workflows/ci.yml
- meson.build
- packages/win_installer/fragment_codecs.iss
- packages/win_installer/fragment_spelling.iss
- packages/win_installer/portable/create-portable.ps1
- src/crash_writer_minidump.cpp
- src/libresrc/meson.build
- src/meson.build
- subprojects/nasm.wrap
- subprojects/packagefiles/luajit/meson.build
- subprojects/packagefiles/luajit/src/host/meson.build
- tools/osx-bundle.sh
- tools/osx-fix-libs.py
- tools/win-installer-setup.ps1
Various small fixes to building and installer generation that came up on arch1t3cht/Aegisub .
The two most "controversial" commits are at the bottom:
- Avisynth is broken anyway (at least for now), so the paths could also just be taken out
- The commit that adds bundling of the hunspell dictionaries downloads them from Sourceforge (mainly to document where they came from), but that download fails quite frequently on the CI. So maybe it's better to just check them into the repo or use some newer dictionary.
> Miscellaneous build fixes

- src/audio_display.cpp
- src/audio_renderer_spectrum.cpp
- src/audio_renderer_spectrum.h
- src/libresrc/default_config.json
- src/libresrc/osx/default_config.json
- src/preferences.cpp
Context: sometimes, for subtitling music videos, it is important to synchronize subtitles to the music. Most of the music energy is located in the bass frequencies, but the current spectrum display packs everything in the 2–3 bottom lines, which is unreadable. Generally, in audio software, spectrum is displayed on a logarithmic frequency scale, spacing octaves linearly, giving more display room for the bass frequencies. Anyway, something in-between linear and log is probably the most suitable for subtitling, showing clearly both the vocal formants and the low-frequency content (bass drum and other instruments).
This patch adds the following:
– Selection of 5 different frequency mappings for the spectrum display, from linear (current default) to logarithmic (octaves are spaced linearly). …
> Spectrum display improvement

- po/zh_TW.po
Currently, the zh_TW locale seems to be "converted" from the zh_CN locale because it contains many Simplified Chinese terminologies and some characters. Thus, it needs some improvements that would take a long time; this patch could be a better version as it only covers a partial improvement, but it should be good enough to see a difference between the current version. I'll find some spare time to make another significant improvement in the future.
> Improve zh_TW Traditional Chinese locale

- meson_options.txt
Fixes this Meson warning when running `meson setup`:
```plain
NOTICE: Future-deprecated features used:
* 1.1.0: {'"boolean option" keyword argument "value" of type str'}
```
> meson_options.txt: give a boolean value to boolean option

- tests/meson.build
Package maintainers won't need to patch Aegisub to use the system version. This also helps Aegisub compile on platforms where the unmodified gtest source doesn't compile but a package is available, such as OpenBSD.
I've tested the conditional branch where gtest is present in the system on OpenBSD. I can't properly test the branch where it isn't present because the subproject doesn't compile on OpenBSD, but I've checked that it tries to compile the subproject.
> use system gtest if available

- src/spellchecker_hunspell.cpp
Since v1.5 (released in Nov. 2016), Hunspell has deprecated C style APIs and added a new set of C++ APIs.  
https://github.com/hunspell/hunspell/compare/v1.4.2...v1.5.3#diff-4c6057a8b7a2e93a0c4e414dfc8ca7cc527ab00ba2b909622bf0d3591fc146b4
Some conversions in `spellchecker_hunspell.cpp` are no longer needed.  
`GetSuggestions()`, with `hunspell->suggest()` in it, had been refactored in Plork's modernization.
> Remove unneeded type conversions in spellchecker_hunspell.cpp

- libaegisub/common/dispatch.cpp
Fixes https://github.com/TypesettingTools/Aegisub/issues/229 .
> Replace some deprecated facilities from Boost.Asio

- tools/version.sh
See the commit message for details.
Also, maybe we don't need to keep track of this SVN revision number stuff now that Aegisub is on git? That would remove a bit of code.
> tools/version.sh: fix compilation of shallow clones

- libaegisub/include/libaegisub/thesaurus.h
I do not see a reason to prefer the flat_map implementation, and it’s causing crashes when compiled with GCC >= 13 and Boost 1.85.0 at optimization level 2 or higher.
Whether or not this is a bug in GCC, or Boost hitting a case of undefined behavior, avoiding it altogether doesn’t seem to hurt.
Fixes #137
> agi: Replace Boost flat_map with std::map in Thesaurus class

- subprojects/boost.wrap
They appear to have moved hosts: https://github.com/boostorg/boost/issues/924
> Fix boost download URL

- src/preferences.cpp
According to the [documentation](https://docs.wxwidgets.org/trunk/interface_2wx_2font_8h.html#a0cd7bfd21a4f901245d3c86d8ea0c080a81d3016e8bbcca1c2f8088f016c44191), wxFONTFAMILY_SWISS = a sans-serif font. However when Windows in zh-CN or zh-TW locales, they're displayed in SimSun（宋体）or PMingLIU（細明體）, both are serif and kinda last fallback fonts in their locales. This bug is ~~clearly attributed to wxWidgets~~ attributed to the backward compatibility of Windows. We could patch it on wxWidgets' side, but we may need a workaround for a couple of years considering wx's release cycle. 
This patch can be applied to @arch1t3cht's and @wangqr's fork.
> Use parent's font for warning text in preferences

- src/MatroskaParser.c
alloca() isn't otherwise available on my Clang build that defaults to non-GNU C++.
> MatroskaParser: include <alloca.h>

- meson.build
Subtle change: this means NDEBUG is defined in subprojects too.
> meson: use b_ndebug instead of -DNDEBUG

- meson.build
- src/MatroskaParser.c
Fixes compilation on OpenBSD and possibly other systems. Appears to partially fix compilation on clang-cl, a subproject still fails for unrelated reasons.
> use feature testing to find alloca()

- meson.build
Meson 0.60.0 was tagged Oct 24, 2021, 4 years ago. This allows us to delete some code.
A quick look at https://repology.org/project/meson/versions says the following maintained systems have a version of Meson older than 0.60.0:
- AlmaLinux 8
- OpenWRT 21.02
- Debian 11
None of these distro releases are the latest, and only Debian packages Aegisub.
> bump minimum Meson to 0.60.0

- src/dialog_dummy_video.cpp
Hello,
This is a trivial fix.
The use of `wxTextValidator` was introduced by upstream commit https://github.com/TypesettingTools/Aegisub/commit/5eb5d1a3391449309c6030c31113082ac80c9945, but w/o the proper include header, i.e. `#include <wx/valtext.h>`.
Error reported on Gentoo GNU/Linux amd64:
```
../aegisub-9999/src/dialog_dummy_video.cpp: In constructor ‘{anonymous}::DialogDummyVideo::DialogDummyVideo(wxWindow*)’: ../aegisub-9999/src/dialog_dummy_video.cpp:120:9: error: ‘wxTextValidator’ was not declared in this scope; did you mean ‘wxValidator’?
120 |         wxTextValidator fpsVal(wxFILTER_INCLUDE_CHAR_LIST, &fps);
|         ^~~~~~~~~~~~~~~
|         wxValidator
../aegisub-9999/src/dialog_dummy_video.cpp:121:9: error: ‘fpsVal’ was not declared in this scope
121 | …
```
> Add missing include header 'wx/valtext.h' for wxTextValidator

- .github/workflows/ci.yml
- libaegisub/ass/uuencode.cpp
- libaegisub/audio/provider_dummy.cpp
- libaegisub/common/cajun/reader.cpp
- libaegisub/common/calltip_provider.cpp
- libaegisub/common/mru.cpp
- libaegisub/common/option.cpp
- libaegisub/common/thesaurus.cpp
- libaegisub/include/libaegisub/lua/ffi.h
- libaegisub/lua/modules/unicode.cpp
- libaegisub/meson.build
- meson.build
- src/MatroskaParser.c
- src/ass_parser.h
- src/ass_style.cpp
- src/audio_timing_dialogue.cpp
- src/base_grid.h
- src/command/command.h
- src/dialog_colorpicker.cpp
- src/frame_main.cpp
- src/main.h
- src/preferences.cpp
- src/spline_curve.cpp
- src/utils.cpp
- src/video_frame.h
PR created to test CI. Commit message below.
----
It seems that Aegisub used to be able to be built without precompiled headers, but this broke with the meson port since there the PCHs are needed to include acconf.h. (On the old build system(s), the feature flags were passed directly as defines to the compiler on Visual Studio, and acconf.h was forcibly included via -include acconf.h with autoconf.)
Some distributions (gentoo in particular) disable PCHs by default for meson due to various bugs, and PCHs can also be quite a headache with language servers (I ended up running an sed one-liner after every configure to replace -include-pch in my compile_commands.json with the respective -include).
Since meson doesn't seem to be able to forcibly include headers for every source file, just pass …
> Allow building without PCHs

- po/make_pot.sh
- po/meson.build
- src/auto4_lua.cpp
- src/command/recent.cpp
- src/menu.cpp
Building Aegisub against wxWidgets trunk (or 3.3.0) has been failing since https://github.com/wxWidgets/wxWidgets/commit/3dddaeb8f2bb8fcfc07d44331a8a2224e24db34a . The updated [doc](https://github.com/wxWidgets/wxWidgets/blob/6561ca020048de57ec28fec5b27f80b00d445cdd/interface/wx/translation.h#L575-L577) said:
> the `_()` macro is defined to do nearly the same thing as `wxGetTranslation()`, with the exception that the argument to `_()` must be a string literal.
Speaking of https://github.com/TypesettingTools/Aegisub/commit/2417c1f488a7fd282d1cf8e4e8966ce18e873a2e. Before applying the fix, the `COMMAND_GROUP` macro will expanded like this :
> Replace `_()` with `wxGetTranslation()` for non-literal strings

- meson.build
> meson: Don't depend on boost's system and regex modules

- src/MatroskaParser.c
Added support for newer display units
The mkv specification was updated at some point to include two more display units in addition to "0" (pixels), "1" (centimeters) and "2" (inches)
check the new specification here:
https://datatracker.ietf.org/doc/rfc9559/
27.9.  Matroska Display Units Registry
Two other values where added, 3 for display aspect ratio and 4 for unkown
Currently Aegisub is unable to open subtitle from files which have these newer values for display unit.
This pr fixes that issue, but I'm not aware if just increasing the number will cause issues else where, but I did not find any other mention of DisplayUnit in the code base other than MatroskaParser.cpp
> Add Support for newer mkv display units

- src/ass_override.cpp
- src/ass_override.h
- src/resolution_resampler.cpp
Stuff that should be obvious from the code:
* `\xbord`, `\xshad`, `\fsp` were scaled wrongly when changing the aspect ratio.
* `\org` and vector drawing coordinates were rounded too coarsely.
* `\pbo` was scaled wrongly when adding/removing margins. It’s a relative baseline offset, not an absolute screen coordinate. (It indeed accepts only integers in all current variants of VSFilter, although it accepts reals in libass.)
* This PR makes no attempt to fix perspective transforms or to take LayoutRes into account. The Perspective Resample automation script remains compatible and remains necessary.
Extra notes:
* `\blur` is impossible to scale perfectly when changing the aspect ratio; we’d need `\xblur` and `\yblur` for that. But this PR makes it scale less (least) badly by using a mean …
> Improve non-perspective resampling

- .github/workflows/ci.yml
These are the cause of the latest macos CI breakage and aren't actually needed for the CI build.
---
PR created to test CI.
> ci: Don't install lua modules on mac
